### PR TITLE
Support for pool filter pump devices

### LINKED ISSUE #23: Support Smart Touch Wifi Filter Pump
Hi! I can successfully onboard with my Bestway app credentials, but it looks like the integration is only for SPAs and not Bestway products in general, because I can't see the pump device I see in my app screen.

Is it the integration or the Bestway Cloud API doesn't expose anything else than SPAs?

### PR DESCRIPTION
**Pull request by phretor**
This should resolve #23

### CODE REVIEW

**Comment by cdpuk** [comment]
Thanks for working out the protocol. This is closely related to #16 so I'll try to take ideas from both in order to come up with something that can scale better as more products and different protocols get released.

I can only see the updates to `bestway.py` in the request. Is there a bunch of other changes missing?

**Comment by phretor** [comment]
Nope. I changed just that.

**Comment by phretor** [comment]
Merged with https://github.com/cdpuk/ha-bestway/tree/generic-bestway

**Comment by phretor** [comment]
@cdpuk I fixed a couple of things in `api.py` and limited the number range to 24 hours. The last thing I don't know how to fix is that the `PoolFilterChangeRequiredSensor` doesn't show up among the entities. Any ideas why?

**Comment by cdpuk** [comment]
Thanks for the updates and test. A few more questions:
* Can you make the API return any other values than "运行中" / "running" for the `status` property. The fact it's a string and not a boolean suggests other values might be possible. At the moment it's forced to a boolean in the integration but that doesn't feel right.
* Is the `error` property always present but typically with a `null` value? Unless you have any idea what errors look like, I might also force this to a `binary_sensor` for now.
* What's the `binary_sensor.spa_errors` entity doing in your screenshot? Unless you have an Airjet spa too, it shouldn't be there.

In other news:
* `PoolFilterChangeRequiredSensor` should be fixed
* An error sensor for the pool filter has been added based on the simple binary interpretation of `error` as above.
* The `generic-bestway` branch has been updated to incorporate all this, and more.

Data is polled from the API every 30s. Changes from the app or device itself should be reflected, but by experimentation this can take a few minutes with my Lay-Z-Spa.

**Comment by phretor** [comment]
> * Can you make the API return any other values than "运行中" / "running" for the `status` property. The fact it's a string and not a boolean suggests other values might be possible. At the moment it's forced to a boolean in the integration but that doesn't feel right.

已停止 / "stopped" is when the unit is not filtering

> * Is the `error` property always present but typically with a `null` value? Unless you have any idea what errors look like, I might also force this to a `binary_sensor` for now.

It's always present with a `0` value when not in error state, but I know there are error codes, so we better assume it's an `int`

> * What's the `binary_sensor.spa_errors` entity doing in your screenshot? Unless you have an Airjet spa too, it shouldn't be there.

Indeed strange. I removed and re-added the integration, but it came back.

> In other news:
> 
> * `PoolFilterChangeRequiredSensor` should be fixed

I still don't see it.

> * An error sensor for the pool filter has been added based on the simple binary interpretation of `error` as above.
> * The `generic-bestway` branch has been updated to incorporate all this, and more.
> 
> Data is polled from the API every 30s. Changes from the app or device itself should be reflected, but by experimentation this can take a few minutes with my Lay-Z-Spa.

**Comment by cdpuk** [comment]
I've made one more change to expose the connectivity sensor, but that shouldn't affect the other entities you're having trouble with.

I spun up a mock API to see what I get, and it all looks correct:
image

Perhaps you could remove the integration and also remove all related entities so you get a clean start when re-adding it? I simply binned my configuration since this is all on a dev instance.

Unless anything else comes up, I'll look to publish this shortly.

**Comment by phretor** [comment]
Nice. I'll try re-adding once you publish, because I've tried already several times with my fork but without luck.

Out of curiosity: what's your development environment and cycle? I used to keep editing the files under the custom_components folder until I reached something functional, and ad that point I rsync-ed back to the repo checkout to add to my fork. That works, but sounds very clumsy. Wondering if there's a more streamlined way.

**Pull request closed without merging**
